spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/limites
    hikari:
      username: postgres
      password: elson
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      hibernate.dll-auto: update
      generate-ddl: true
      show-sql: true
    generate-ddl: true